version: "3.8"

services:
  node-app:
    build: ./node
    ports:
      - ${NODE_APP_PORT_HOST}:${NODE_APP_PORT_CONTAINER}
    volumes:
      - ./node/src:/app/src
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${MYADMIN_PORT_HOST}:${MYADMIN_PORT_CONTAINER}
