version: "3"

services:
  node-app:
    build: ./
    container_name: ${APP_NAME}_server
    ports:
      - ${NODE_APP_PORT_HOST}:${NODE_APP_PORT_CONTAINER}
    volumes:
      - ./node:/app
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: mysql:8
    container_name: ${APP_NAME}_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: ${APP_NAME}_admin
    ports:
      - ${MYADMIN_PORT_HOST}:${MYADMIN_PORT_CONTAINER}
